config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  devise_for :users
  devise_scope :user do
    delete '/sign_out', to: 'devise/sessions#destroy', as: 'sign_out'
    get '/sign_in', to: 'devise/sessions#new', as: 'sign_in'
    get '/users/sign_in', to: 'devise/sessions#new', as: 'users_sign_in'
    get '/sign_up', to: 'devise/registrations#new', as: 'sign_up'
    get '/reset_password', to: 'devise/passwords#new', as: 'reset_password'
  end

  resources :gadgets
end

app/models/gadget.rb
class Gadget < ActiveRecord::Base
  belongs_to :user
  has_many :photos, inverse_of: :gadget, dependent: :destroy

  accepts_nested_attributes_for :photos, allow_destroy: true

  def self.search_by_name_or_description(keyword)
    where('name iLIKE ? OR description iLIKE ?', "%#{keyword}%", "%#{keyword}%")
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :gadget

  validates :gadget, presence: true

  mount_uploader :image, PhotoUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :gadgets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gadgets_controller.rb
class GadgetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_gadget, only: [:edit, :update, :destroy, :show]

  def index
    @gadgets = current_user.gadgets

    if params[:search]
      @gadgets = @gadgets.search_by_name_or_description(params[:search])
    end
  end

  def new
    @gadget = Gadget.new
  end

  def create
    @gadget = Gadget.new(user_id: current_user.id)

    if @gadget.update_attributes(gadget_params)
      handle_images_upload

      flash[:success] = 'Saved'
      redirect_to gadgets_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @gadget.update_attributes(gadget_params)
      handle_images_upload

      flash[:success] = 'Updated'
      redirect_to edit_gadget_path(@gadget)
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @gadget.destroy

    flash[:success] = 'Deleted'
    redirect_to gadgets_path
  end

  private

  def handle_images_upload
    if params[:images]
      params[:images].each do |image|
        @gadget.photos.create(image: image)
      end
    end
  end

  def set_gadget
    @gadget = Gadget.find_by(id: params[:id], user_id: current_user.id)
  end

  def gadget_params
    params.require(:gadget).permit(:name, :description)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gadgets_helper.rb
module GadgetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gadgets/_form.html.erb
<%= form_for @gadget, html: { multipart: true } do |f| %>
  <table class="table table-striped">
    <tr>
      <td><%= f.label :name %></td>
      <td><%= f.text_field :name, class: 'input-xxlarge' %></td>
    </tr>
    <tr>
      <td><%= f.label :description %></td>
      <td><%= f.text_area :description, class: 'input-xxlarge', rows: 5 %></td>
    </tr>
    <tr>
      <td>Images</td>
      <td><%= file_field_tag 'images[]', type: :file, multiple: true %></td>
    </tr>
    <tr>
      <td></td>
      <td>
        <%= f.submit 'Save', class: 'btn btn-success' %>
      </p>
    </tr>
  </table>
<% end %>

<%= link_to 'Back to list', gadgets_path %>

app/views/gadgets/edit.html.erb
<h1>Edit <%= @gadget.name %></h1>

<%= render 'form', gadget: @gadget %>

app/views/gadgets/index.html.erb
<h1>Gadgets</h1>

<div class="alert">
  <%= form_tag gadgets_path, method: :get do %>
    <%= text_field_tag :search, params[:search], placeholder: 'search by name or description' %>
    <br>
    <%= submit_tag 'Search', name: nil, class: 'btn btn-primary' %>
    <%= link_to 'Reset search', gadgets_path %>
  <% end %>
</div>

<p>
  <%= link_to 'Add new', new_gadget_path, class: 'btn' %>
</p>

<table class="table table-striped">
  <tr>
    <th width="200px">Image</th>
    <th>Name</th>
    <th>Description</th>
    <th>Action</th>
  </tr>
  <% @gadgets.each do |gadget| %>
      <tr>
        <td>
          <% gadget.photos.each do |photo| %>
            <%= image_tag photo.image_url(:thumb).to_s %>
          <% end %>
        </td>
        <td><%= gadget.name %></td>
        <td><%= gadget.description %></td>
        <td>
          <%= link_to 'Edit', edit_gadget_path(gadget) %>
          <%= link_to 'Delete', gadget_path(gadget), method: :delete %>
        </td>
      </tr>
  <% end %>
  <% unless @gadgets.present? %>
  <tr>
    <td>
      No results.
    </td>
  </tr>
  <% end %>
</table>

<%= link_to 'Go to welcome page', root_path, class: 'btn btn-warning' %>
<%= link_to 'Sign out', sign_out_path, method: :delete, class: 'btn btn-danger' %>

app/views/gadgets/new.html.erb
<h1>New Gadget</h1>

<%= render 'form', gadget: @gadget %>

app/views/gadgets/show.html.erb
<h1>Gadgets#show</h1>
<p>Find me in app/views/gadgets/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Electronic Gadgets Collection</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% flash.each do |name, msg| %>
    <p class="alert alert-<%= name %>"><%= msg %></p>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to Electronic Gadgets Collection</h1>
<p class="alert">Once signed up, you can have your own gadgets online!</p>

<% if user_signed_in? %>
  <%= link_to 'Sign out', sign_out_path, method: :delete, class: 'btn btn-danger' %>
  <%= link_to 'See your gadgets', gadgets_path, class: 'btn btn-primary' %>
<% else %>
  <%= link_to 'Sign up', sign_up_path %> or <%= link_to 'Sign in', sign_in_path %>
<% end %>